version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  analyze:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  version: 2
  main:
    jobs:
      - analyze
